version:  '3'

services:
  ta:
    image: traffic-assistant:latest
    container_name: MAIN-MODULE
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - eureka.instance.hostname=MAIN-MODULE
  eureka:
    image: service-registry:latest
    container_name: eureka
    ports:
      - "8761:8761"
  users:
    image: user-service:latest
    container_name: USER-SERVICE
    ports:
      - "9090:9090"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - eureka.instance.hostname=USER-SERVICE